{
 "title": "new dashboard",
 "time": { "from": "now-7d", "to": "now" },
 "panels": [
  {
   "title": "Total Events",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({job=\"cowrie\"} [$__range]))"
    }
   ]
  },
  {
   "title": "Top 10 Attacking IPs",
   "type": "stat",
   "gridPos": { "h": 10, "w": 11, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(10, sum by (src_ip) (count_over_time({job=\"cowrie\"} | json | src_ip != \"\" [$__range])))"
    }
   ]
  },
  {
   "title": "Attack events over time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(count_over_time({job=\"cowrie\"} [5m]))"
    }
   ]
  },
  {
   "title": "Events by Type",
   "type": "piechart",
   "gridPos": { "h": 12, "w": 11, "x": 12, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (eventid) (count_over_time({job=\"cowrie\"} | json [$__range]))"
    }
   ]
  }
 ]
}